services:
  # Backend: Node.js + Express + Socket.IO
  - type: web
    name: live-polling-backend
    env: node
    branch: main
    rootDir: Intervue-Assignment/server
    buildCommand: "npm install"
    startCommand: "npm run server"   # correct if "server" script exists in package.json
    autoDeploy: true
    region: oregon
    plan: free

  # Frontend: React + Vite (Static Site)
  - type: web
    name: live-polling-frontend
    env: static
    branch: main
    rootDir: Intervue-Assignment
    buildCommand: "npm install && npm run build"   # <-- build once
    staticPublishPath: "dist"                      # <-- serve built files
    autoDeploy: true
    region: oregon
    plan: free
