services:
  # Backend: Node.js + Express + Socket.IO
  - type: web
    name: live-polling-backend
    env: node
    branch: main
    rootDir: Intervue-Assignment/server
    buildCommand: "npm install"
    startCommand: "npm run server"   # backend start script
    autoDeploy: true
    region: oregon
    plan: free

  # Frontend: React + Vite (Static Site)
  - type: web
    name: live-polling-frontend
    env: static
    branch: main
    rootDir: Intervue-Assignment
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    autoDeploy: true
    plan: free
